name: Laravel

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ftp.ancerl.co.za
    #     username: adeelftp@ancerl.co.za
    #     password: Adeel@ftp1234
    #     server-dir: '/restaurant/'


    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.mysql
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: database/database.mysql
      run: vendor/bin/phpunit