name: Laravel

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Enviroment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
     - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
              username: ${{ secrets.FTP_USERNAME}}
              host: ${{ secrets.FTP_SERVER }}
              key: ${{secrets.FTP_PASSWORD}}
              script: |
                      cd /var/www/html/restaurant
                      git checkout -f
                      git pull
                      php artisan migrate 